<?php

/**
 * sfGuardRememberKey
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    net.daheardit-records.www
 * @subpackage model
 * @author     Constructions Incongrues <contact@constructions-incongrues.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardRememberKey extends PluginsfGuardRememberKey
{
}
