apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: model
  namespace: dhr
spec:
  owner: default/constructions-incongrues-net
  targets:
    - model/api/rest.yaml
    - model/component/symfony.yaml
    - model/system/web.yaml
  