apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: model
  namespace: dhr
spec:
  targets:
    - ./model/api/rest.yaml
    - ./model/component/symfony.yaml
    - ./model/resource/database.yaml
    - ./model/resource/disk.yaml
    - ./model/system/web.yaml
  owner: default/constructions-incongrues-net