version: '3'

services:
  adminer:
    depends_on:
      - db
    image: adminer
    labels:
        traefik.frontend.rule: "Host:adminer.daheardit.localhost"
        traefik.port: "8080"
    restart: always

  db:
    environment:
      MYSQL_DATABASE: daheardit
      MYSQL_ROOT_PASSWORD: root
    image: mysql:5.6
    volumes:
      - ./src/data/fixtures/net_dahearditrecords_www.dump.sql:/docker-entrypoint-initdb.d/daheardit.sql

  php:
    build: .
    command: ["php", "-S", "0.0.0.0:8000", "-t", "web"]
    depends_on:
      - db
    image: constructionsincongrues/dahearditrecords
    labels:
      traefik.frontend.rule: "Host:daheardit.localhost"
      traefik.port: "8000"
    volumes:
      - ./src:/usr/local/src

  traefik:
    command: --api --docker
    image: traefik:1.7
    labels:
      traefik.frontend.rule: "Host:traefik.daheardit.localhost"
      traefik.port: "8080"
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
