version: '3'

services:
  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8080:8080

  db:
    environment:
      MYSQL_DATABASE: daheardit
      MYSQL_ROOT_PASSWORD: root
    image: mysql:5.6
    volumes:
      - ./src/data/fixtures/net_dahearditrecords_www.dump.sql:/docker-entrypoint-initdb.d/daheardit.sql

  nginx:
    depends_on: 
      - php
    image: nginx:1.15-alpine
    ports:
      - 8081:80
    volumes:
      - ./etc/docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src/web:/usr/local/src/app/src/web

  php:
    build: .
    depends_on:
      - db
    image: constructionsincongrues/daheardit-php
    volumes:
      - ./src:/usr/local/src/app/src
