<?php

/**
 * ArtistTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArtistTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ArtistTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Artist');
    }

	public function findOneBySlugAndCulture($slug, $culture = 'fr')
	{
		$q = $this->createQuery('a')
			->where('a.slug = ?', $slug)
            ->leftJoin('a.Translation t ON a.id = t.artist_id')
            ->andWhere('t.lang = ?', $culture);

		return $q->fetchOne();
	}

}
