<?php

/**
 * HeaderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HeaderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HeaderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Header');
    }
}