<?php

/**
 * ReleaseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReleaseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReleaseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Release');
    }
}