<?php

/**
 * ReleaseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReleaseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReleaseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Release');
    }

	public function findOneBySlugAndCulture($slug, $culture = 'fr')
	{
		$q = $this->createQuery('r')
			->where('r.slug = ?', $slug)
            ->leftJoin('r.Artist a')
			->leftJoin('r.ArtworkArtist aa')
			->leftJoin('r.Translation t')
			->andWhere('t.lang = ?', $culture);

		return $q->fetchOne();
	}

	public function findLatest($public = true)
	{
		$q = $this->createQuery('r')
            ->innerJoin('r.Artist a')
            ->orderBy('r.sku desc')
            ->limit(1);
        if ($public) {
        	$q = $q->where('r.is_public = 1');
        }

		return $q->fetchOne();
	}
}