generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Post
    theme:                 twitter
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          post
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        title:
          label: Titre
          help: Le titre de la news
        body:
          label: Contenu
          help: Le contenu de la news
        image:
          label: Image
          help: L'image associée à la news
      list:
        display: [=title, created_at]
      filter:  ~
      form:
        display: [en, fr, image]
      edit:    ~
      new:     ~
