generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Release
    theme:                 twitter
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          release
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        title:
          label: Titre
          help: Le titre de la sortie
        sku:
          label: sku
          help: La référence catalogue
      list:
        display: [=sku, title, artist]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
