generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Release
    theme:                 twitter
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          release
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        title:
          label: Titre
          help: Le titre de la sortie
        sku:
          label: sku
          help: La référence catalogue
        slug:
          label: slug
          help: La référence catalogue
        released_at:
          label: Date de sortie
          help: La date de sortie officielle
        price:
          label: Prix
          help: Le prix et les identifiants Paypal des différents formats de la release (en euros). Un par ligne. Format : format,prix,id_paypal
        is_available:
          label: La release est-elle encore disponible ?
          help: Décocher cette case si la release est épuisée
        links_carousel:
          label : Liens carousel
          help: Un lien par ligne
        url_header:
          label : URL du header
          help: Lien vers lequel pointera le header
        license:
          label : Licence
          help: HTML décrivant la licence de la sortie
      list:
        display: [=sku, title, artist, artwork_artist, released_at]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
