generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Release
    theme:                 twitter
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          release
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        title:
          label: Titre
          help: Le titre de la sortie
        sku:
          label: sku
          help: La référence catalogue
        slug:
          label: slug
          help: La référence catalogue
        released_at:
          label: Date de sortie
          help: La date de sortie officielle
        price:
          label: Prix
          help: Le prix de la release en euros
        is_available:
          label: La release est-elle encore disponible ?
          help: Décocher cette case si la release est épuisée 
      list:
        display: [=sku, title, artist, released_at]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
