<?php

/**
 * BaseTrack
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $release_id
 * @property Release $Release
 * 
 * @method string  getName()       Returns the current record's "name" value
 * @method integer getReleaseId()  Returns the current record's "release_id" value
 * @method Release getRelease()    Returns the current record's "Release" value
 * @method Track   setName()       Sets the current record's "name" value
 * @method Track   setReleaseId()  Sets the current record's "release_id" value
 * @method Track   setRelease()    Sets the current record's "Release" value
 * 
 * @package    net.daheardit-records.www
 * @subpackage model
 * @author     Constructions Incongrues <contact@constructions-incongrues.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTrack extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('track');
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('release_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Release', array(
             'local' => 'release_id',
             'foreign' => 'id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($sluggable0);
        $this->actAs($timestampable0);
    }
}