<?php

/**
 * BaseContent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $informations
 * @property string $credits
 * @property string $greetings
 * @property string $video
 * @property string $links
 * 
 * @method string  getInformations() Returns the current record's "informations" value
 * @method string  getCredits()      Returns the current record's "credits" value
 * @method string  getGreetings()    Returns the current record's "greetings" value
 * @method string  getVideo()        Returns the current record's "video" value
 * @method string  getLinks()        Returns the current record's "links" value
 * @method Content setInformations() Sets the current record's "informations" value
 * @method Content setCredits()      Sets the current record's "credits" value
 * @method Content setGreetings()    Sets the current record's "greetings" value
 * @method Content setVideo()        Sets the current record's "video" value
 * @method Content setLinks()        Sets the current record's "links" value
 * 
 * @package    net.daheardit-records.www
 * @subpackage model
 * @author     Constructions Incongrues <contact@constructions-incongrues.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('content');
        $this->hasColumn('informations', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('credits', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('greetings', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('video', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('links', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'informations',
              1 => 'credits',
              2 => 'greetings',
             ),
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($i18n0);
        $this->actAs($timestampable0);
    }
}