<?php

/**
 * BaseHeader
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $url
 * @property boolean $enabled
 * 
 * @method string  getUrl()     Returns the current record's "url" value
 * @method boolean getEnabled() Returns the current record's "enabled" value
 * @method Header  setUrl()     Sets the current record's "url" value
 * @method Header  setEnabled() Sets the current record's "enabled" value
 * 
 * @package    net.daheardit-records.www
 * @subpackage model
 * @author     Constructions Incongrues <contact@constructions-incongrues.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHeader extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('header');
        $this->hasColumn('url', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('enabled', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}