<?php

/**
 * BaseComponent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property varchar $name
 * @property boolean $is_activated
 * @property text $description
 * 
 * @method varchar   getName()         Returns the current record's "name" value
 * @method boolean   getIsActivated()  Returns the current record's "is_activated" value
 * @method text      getDescription()  Returns the current record's "description" value
 * @method Component setName()         Sets the current record's "name" value
 * @method Component setIsActivated()  Sets the current record's "is_activated" value
 * @method Component setDescription()  Sets the current record's "description" value
 * 
 * @package    net.daheardit-records.www
 * @subpackage model
 * @author     Constructions Incongrues <contact@constructions-incongrues.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseComponent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('component');
        $this->hasColumn('name', 'varchar', null, array(
             'type' => 'varchar',
             ));
        $this->hasColumn('is_activated', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('description', 'text', null, array(
             'type' => 'text',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}