<?php

/**
 * BaseArtist
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $url
 * @property string $presentation
 * @property Doctrine_Collection $Release
 * 
 * @method string              getName()         Returns the current record's "name" value
 * @method string              getUrl()          Returns the current record's "url" value
 * @method string              getPresentation() Returns the current record's "presentation" value
 * @method Doctrine_Collection getRelease()      Returns the current record's "Release" collection
 * @method Artist              setName()         Sets the current record's "name" value
 * @method Artist              setUrl()          Sets the current record's "url" value
 * @method Artist              setPresentation() Sets the current record's "presentation" value
 * @method Artist              setRelease()      Sets the current record's "Release" collection
 * 
 * @package    net.daheardit-records.www
 * @subpackage model
 * @author     Constructions Incongrues <contact@constructions-incongrues.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArtist extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('artist');
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('url', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('presentation', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Release', array(
             'local' => 'id',
             'foreign' => 'artist_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'presentation',
             ),
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($sluggable0);
        $this->actAs($i18n0);
        $this->actAs($timestampable0);
    }
}