<?php

/**
 * BaseRelease
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $sku
 * @property string $slug
 * @property date $released_at
 * @property string $presentation
 * @property string $license
 * @property string $links_carousel
 * @property string $url_header
 * @property boolean $is_public
 * @property boolean $is_new
 * @property string $image1
 * @property string $image2
 * @property integer $artist_id
 * @property integer $artwork_artist_id
 * @property string $paypal_id
 * @property boolean $is_available
 * @property string $price
 * @property text $links_press
 * @property text $links_streaming
 * @property Artist $Artist
 * @property ArtworkArtist $ArtworkArtist
 * @property Doctrine_Collection $Track
 * 
 * @method string              get()                  Returns the current record's "title" value
 * @method string              get()                  Returns the current record's "sku" value
 * @method string              get()                  Returns the current record's "slug" value
 * @method date                get()                  Returns the current record's "released_at" value
 * @method string              get()                  Returns the current record's "presentation" value
 * @method string              get()                  Returns the current record's "license" value
 * @method string              get()                  Returns the current record's "links_carousel" value
 * @method string              get()                  Returns the current record's "url_header" value
 * @method boolean             get()                  Returns the current record's "is_public" value
 * @method boolean             get()                  Returns the current record's "is_new" value
 * @method string              get()                  Returns the current record's "image1" value
 * @method string              get()                  Returns the current record's "image2" value
 * @method integer             get()                  Returns the current record's "artist_id" value
 * @method integer             get()                  Returns the current record's "artwork_artist_id" value
 * @method string              get()                  Returns the current record's "paypal_id" value
 * @method boolean             get()                  Returns the current record's "is_available" value
 * @method string              get()                  Returns the current record's "price" value
 * @method text                get()                  Returns the current record's "links_press" value
 * @method text                get()                  Returns the current record's "links_streaming" value
 * @method Artist              get()                  Returns the current record's "Artist" value
 * @method ArtworkArtist       get()                  Returns the current record's "ArtworkArtist" value
 * @method Doctrine_Collection get()                  Returns the current record's "Track" collection
 * @method Release             set()                  Sets the current record's "title" value
 * @method Release             set()                  Sets the current record's "sku" value
 * @method Release             set()                  Sets the current record's "slug" value
 * @method Release             set()                  Sets the current record's "released_at" value
 * @method Release             set()                  Sets the current record's "presentation" value
 * @method Release             set()                  Sets the current record's "license" value
 * @method Release             set()                  Sets the current record's "links_carousel" value
 * @method Release             set()                  Sets the current record's "url_header" value
 * @method Release             set()                  Sets the current record's "is_public" value
 * @method Release             set()                  Sets the current record's "is_new" value
 * @method Release             set()                  Sets the current record's "image1" value
 * @method Release             set()                  Sets the current record's "image2" value
 * @method Release             set()                  Sets the current record's "artist_id" value
 * @method Release             set()                  Sets the current record's "artwork_artist_id" value
 * @method Release             set()                  Sets the current record's "paypal_id" value
 * @method Release             set()                  Sets the current record's "is_available" value
 * @method Release             set()                  Sets the current record's "price" value
 * @method Release             set()                  Sets the current record's "links_press" value
 * @method Release             set()                  Sets the current record's "links_streaming" value
 * @method Release             set()                  Sets the current record's "Artist" value
 * @method Release             set()                  Sets the current record's "ArtworkArtist" value
 * @method Release             set()                  Sets the current record's "Track" collection
 * 
 * @package    net.daheardit-records.www
 * @subpackage model
 * @author     Constructions Incongrues <contact@constructions-incongrues.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRelease extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('release');
        $this->hasColumn('title', 'string', null, array(
             'type' => 'string',
             'notblank' => true,
             ));
        $this->hasColumn('sku', 'string', null, array(
             'type' => 'string',
             'notblank' => true,
             ));
        $this->hasColumn('slug', 'string', null, array(
             'type' => 'string',
             'notblank' => true,
             ));
        $this->hasColumn('released_at', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('presentation', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('license', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('links_carousel', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('url_header', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('is_public', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('is_new', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('image1', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('image2', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('artist_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('artwork_artist_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('paypal_id', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('is_available', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('price', 'string', null, array(
             'type' => 'string',
             'notblank' => true,
             'default' => 5,
             ));
        $this->hasColumn('links_press', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('links_streaming', 'text', null, array(
             'type' => 'text',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Artist', array(
             'local' => 'artist_id',
             'foreign' => 'id'));

        $this->hasOne('ArtworkArtist', array(
             'local' => 'artwork_artist_id',
             'foreign' => 'id'));

        $this->hasMany('Track', array(
             'local' => 'id',
             'foreign' => 'release_id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'presentation',
             ),
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($i18n0);
        $this->actAs($timestampable0);
    }
}