<?php

/**
 * BaseRelease
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $sku
 * @property date $released_at
 * @property string $presentation
 * @property boolean $is_public
 * @property boolean $is_new
 * @property string $image1
 * @property string $image2
 * @property integer $artist_id
 * @property string $paypal_id
 * @property Artist $Artist
 * @property Doctrine_Collection $Track
 * 
 * @method string              getTitle()        Returns the current record's "title" value
 * @method string              getSku()          Returns the current record's "sku" value
 * @method date                getReleasedAt()   Returns the current record's "released_at" value
 * @method string              getPresentation() Returns the current record's "presentation" value
 * @method boolean             getIsPublic()     Returns the current record's "is_public" value
 * @method boolean             getIsNew()        Returns the current record's "is_new" value
 * @method string              getImage1()       Returns the current record's "image1" value
 * @method string              getImage2()       Returns the current record's "image2" value
 * @method integer             getArtistId()     Returns the current record's "artist_id" value
 * @method string              getPaypalId()     Returns the current record's "paypal_id" value
 * @method Artist              getArtist()       Returns the current record's "Artist" value
 * @method Doctrine_Collection getTrack()        Returns the current record's "Track" collection
 * @method Release             setTitle()        Sets the current record's "title" value
 * @method Release             setSku()          Sets the current record's "sku" value
 * @method Release             setReleasedAt()   Sets the current record's "released_at" value
 * @method Release             setPresentation() Sets the current record's "presentation" value
 * @method Release             setIsPublic()     Sets the current record's "is_public" value
 * @method Release             setIsNew()        Sets the current record's "is_new" value
 * @method Release             setImage1()       Sets the current record's "image1" value
 * @method Release             setImage2()       Sets the current record's "image2" value
 * @method Release             setArtistId()     Sets the current record's "artist_id" value
 * @method Release             setPaypalId()     Sets the current record's "paypal_id" value
 * @method Release             setArtist()       Sets the current record's "Artist" value
 * @method Release             setTrack()        Sets the current record's "Track" collection
 * 
 * @package    net.daheardit-records.www
 * @subpackage model
 * @author     Constructions Incongrues <contact@constructions-incongrues.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRelease extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('release');
        $this->hasColumn('title', 'string', null, array(
             'type' => 'string',
             'notblank' => true,
             ));
        $this->hasColumn('sku', 'string', null, array(
             'type' => 'string',
             'notblank' => true,
             ));
        $this->hasColumn('released_at', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('presentation', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('is_public', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('is_new', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('image1', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('image2', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('artist_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('paypal_id', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Artist', array(
             'local' => 'artist_id',
             'foreign' => 'id'));

        $this->hasMany('Track', array(
             'local' => 'id',
             'foreign' => 'release_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'title',
             ),
             ));
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'presentation',
             ),
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($sluggable0);
        $this->actAs($i18n0);
        $this->actAs($timestampable0);
    }
}