<?php

/**
 * BaseContent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $informations
 * @property string $greetings
 * @property string $links1
 * @property string $links2
 * @property string $footer_video
 * @property string $url_header
 * 
 * @method string  getInformations() Returns the current record's "informations" value
 * @method string  getGreetings()    Returns the current record's "greetings" value
 * @method string  getLinks1()       Returns the current record's "links1" value
 * @method string  getLinks2()       Returns the current record's "links2" value
 * @method string  getFooterVideo()  Returns the current record's "footer_video" value
 * @method string  getUrlHeader()    Returns the current record's "url_header" value
 * @method Content setInformations() Sets the current record's "informations" value
 * @method Content setGreetings()    Sets the current record's "greetings" value
 * @method Content setLinks1()       Sets the current record's "links1" value
 * @method Content setLinks2()       Sets the current record's "links2" value
 * @method Content setFooterVideo()  Sets the current record's "footer_video" value
 * @method Content setUrlHeader()    Sets the current record's "url_header" value
 * 
 * @package    net.daheardit-records.www
 * @subpackage model
 * @author     Constructions Incongrues <contact@constructions-incongrues.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('content');
        $this->hasColumn('informations', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('greetings', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('links1', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('links2', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('footer_video', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('url_header', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'informations',
              1 => 'credits',
              2 => 'greetings',
             ),
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($i18n0);
        $this->actAs($timestampable0);
    }
}