<?php

/**
 * BaseComponent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property varchar $label
 * @property varchar $status
 * @property text $description
 * 
 * @method varchar   getLabel()       Returns the current record's "label" value
 * @method varchar   getStatus()      Returns the current record's "status" value
 * @method text      getDescription() Returns the current record's "description" value
 * @method Component setLabel()       Sets the current record's "label" value
 * @method Component setStatus()      Sets the current record's "status" value
 * @method Component setDescription() Sets the current record's "description" value
 * 
 * @package    net.daheardit-records.www
 * @subpackage model
 * @author     Constructions Incongrues <contact@constructions-incongrues.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseComponent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('component');
        $this->hasColumn('label', 'varchar', null, array(
             'type' => 'varchar',
             ));
        $this->hasColumn('status', 'varchar', null, array(
             'type' => 'varchar',
             ));
        $this->hasColumn('description', 'text', null, array(
             'type' => 'text',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}