<?php

/**
 * BaseArtworkArtist
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $url
 * @property string $image
 * @property string $presentation
 * @property string $links_carousel
 * @property string $more
 * @property boolean $is_public
 * @property Doctrine_Collection $Release
 * 
 * @method string              getName()           Returns the current record's "name" value
 * @method string              getUrl()            Returns the current record's "url" value
 * @method string              getImage()          Returns the current record's "image" value
 * @method string              getPresentation()   Returns the current record's "presentation" value
 * @method string              getLinksCarousel()  Returns the current record's "links_carousel" value
 * @method string              getMore()           Returns the current record's "more" value
 * @method boolean             getIsPublic()       Returns the current record's "is_public" value
 * @method Doctrine_Collection getRelease()        Returns the current record's "Release" collection
 * @method ArtworkArtist       setName()           Sets the current record's "name" value
 * @method ArtworkArtist       setUrl()            Sets the current record's "url" value
 * @method ArtworkArtist       setImage()          Sets the current record's "image" value
 * @method ArtworkArtist       setPresentation()   Sets the current record's "presentation" value
 * @method ArtworkArtist       setLinksCarousel()  Sets the current record's "links_carousel" value
 * @method ArtworkArtist       setMore()           Sets the current record's "more" value
 * @method ArtworkArtist       setIsPublic()       Sets the current record's "is_public" value
 * @method ArtworkArtist       setRelease()        Sets the current record's "Release" collection
 * 
 * @package    net.daheardit-records.www
 * @subpackage model
 * @author     Constructions Incongrues <contact@constructions-incongrues.net>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArtworkArtist extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('artwork_artist');
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             'notblank' => true,
             ));
        $this->hasColumn('url', 'string', null, array(
             'type' => 'string',
             'regexp' => '|^http(s)?://[a-z0-9-]+(.[a-z0-9-]+)*(:[0-9]+)?(/.*)?$|',
             ));
        $this->hasColumn('image', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('presentation', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('links_carousel', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('more', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('is_public', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Release', array(
             'local' => 'id',
             'foreign' => 'artwork_artist_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'presentation',
             ),
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($sluggable0);
        $this->actAs($i18n0);
        $this->actAs($timestampable0);
    }
}