apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: symfony
  namespace: dhr
  annotations:
    github.com/project-slug: constructions-incongrues/net.daheardit-records.www
spec:
  type: website
  lifecycle: production
  system: dhr/web
  owner: default/constructions-incongrues.net
