all:
  sf_twitter_bootstrap:
    site:                   "Da ! Heard It Records"
    top_link_to_fieldset:   true
    display_top_pagination: true
    use_icons_in_button:    true
    with_show:              true
    categories:
      Artistes:
        items:
          Lister:
            url:              artist
            image:            user.png
          Créer:
            url:              artist_new
            image:            user.png

      Graphistes:
        items:
          Lister:
            url:              artwork_artist
            image:            user.png
          Créer:
            url:              artwork_artist_new
            image:            user.png

      Sorties:
        items:
          Lister:
            url:              release
            image:            music.png
          Créer:
            url:              release_new
            image:            music.png

      Contenus:
        items:
          Lister:
            url:              content
            image:            pencil.png
          Créer:
            url:              content_new
            image:            pencil.png
          "Invalider le cache":
            url:              content_clearCache
            image:            button-synchronize.png

