artwork_artist:
  class: sfDoctrineRouteCollection
  options:
    model:                ArtworkArtist
    module:               artwork_artist
    prefix_path:          /artwork_artist
    column:               id
    with_wildcard_routes: true

content:
  class: sfDoctrineRouteCollection
  options:
    model:                Content
    module:               content
    prefix_path:          /content
    column:               id
    with_wildcard_routes: true

content_clearCache:
  url:   /content/clearCache
  param: { module: content, action: clearCache }

post:
  class: sfDoctrineRouteCollection
  options:
    model:                Post
    module:               post
    prefix_path:          /post
    column:               id
    with_wildcard_routes: true

release:
  class: sfDoctrineRouteCollection
  options:
    model:                Release
    module:               release
    prefix_path:          /release
    column:               id
    with_wildcard_routes: true

artist:
  class: sfDoctrineRouteCollection
  options:
    model:                Artist
    module:               artist
    prefix_path:          /artist
    column:               id
    with_wildcard_routes: true

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_register:
  url:   /register
  param: { module: sfGuardRegister, action: index }

sf_guard_forgot_password:
  url:   /forgot_password
  param: { module: sfGuardForgotPassword, action: index }

sf_guard_forgot_password_change:
  url:   /forgot_password/:unique_key
  class: sfDoctrineRoute
  options: { model: sfGuardForgotPassword, type: object }
  param: { module: sfGuardForgotPassword, action: change }
  requirements:
    sf_method: [get, post]

# default rules
homepage:
  url:   /
  param: { module: sfTwitterBootstrap, action: dashboard }
