# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# main
main_thanks:
  url: /thanks
  param: { module: main, action: thanks }

# feeds
feeds_posts:
  url: /:sf_culture/feeds/posts
  param: { module: feeds, action: posts }
  requirements:
    sf_culture: (?:fr|en)

# post
post_show:
  url: /post/:slug
  param: { module: post, action: show }

# artist
artist_show:
  url:   /:sf_culture/artist/:slug
  param: { module: artist, action: show }
  requirements:
    sf_culture: (?:fr|en)

# artwork_artist
artwork_artist_show:
  url:   /:sf_culture/illustrator/:slug
  param: { module: artwork_artist, action: show }
  requirements:
    sf_culture: (?:fr|en)

# release
release_show:
  url:   /:sf_culture/discography/:slug
  param: { module: release, action: show }
  requirements:
    sf_culture: (?:fr|en)

release_track_show:
  url:   /:sf_culture/discography/:slug/:number
  param: { module: release, action: showTrack }
  requirements:
    sf_culture: (?:fr|en)

# homepage
homepage_localized:
  url:   /:sf_culture/
  param: { module: main, action: index }
  requirements:
    sf_culture: (?:fr|en)

homepage_localized_noslash:
  url:   /:sf_culture
  param: { module: main, action: index }
  requirements:
    sf_culture: (?:fr|en)

homepage:
  url:   /
  param: { module: main, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
