detect_relations: true

Artist:
  actAs:
    Sluggable:
      fields: [name]
    I18n:
      fields: [presentation]
    Timestampable: ~
  columns:
    name:         
      type:     string
      notblank: true
    url:
      type: string
      regexp: "|^http(s)?://[a-z0-9-]+(.[a-z0-9-]+)*(:[0-9]+)?(/.*)?$|"
    image:        string
    presentation: string
    links_carousel: text
    more:        string
    is_public:
      type:       boolean
      default:    1

Release:
  actAs:
    Sluggable:
      fields: [title]
    I18n:
      fields: [presentation]
    Timestampable: ~
  columns:
    title:
      type:     string
      notblank: true
    sku:
      type:     string
      notblank: true
    released_at:  date
    presentation: string
    is_public:
      type:       boolean
      default:    1
    is_new:
      type:       boolean
      default:    0
    image1:       string
    image2:       string
    artist_id:    integer
    paypal_id:    string
    is_available:
      type:       boolean
      default:    1
    price:
      type:     integer
      notblank: true
      default:  5

Track:
  actAs:
    Sluggable:
      fields: [title]
    Timestampable: ~
  columns:
    title:      string
    number:     integer
    release_id: integer

Post:
  actAs:
    Sluggable:
      fields: [title]
    I18n:
      fields: [title, body]
    Timestampable: ~
  columns:
    title:
      type:     string
      notblank: true
    body: 
      type:     string
      notblank: true
    image:
      type:     string
      notblank: true

Content:
  actAs:
    I18n:
      fields: [informations, credits, greetings]
    Timestampable: ~
  columns:
    informations: string
    greetings:    string
    links1:       string
    links2:       string
    footer_video: string
