detect_relations: true

Artist:
  actAs:
    Sluggable:
      fields: [name]
    I18n:
      fields: [presentation]
    Timestampable: ~
  columns:
    name:         
      type:     string
      notblank: true
    url:
      type: string
      regexp: "|^http(s)?://[a-z0-9-]+(.[a-z0-9-]+)*(:[0-9]+)?(/.*)?$|"
    image:        string
    presentation: string
    is_public:
      type:       boolean
      default:    1

Release:
  actAs:
    Sluggable:
      fields: [title]
    I18n:
      fields: [presentation]
    Timestampable: ~
  columns:
    title:
      type:     string
      notblank: true
    sku:
      type:     string
      notblank: true
    released_at:  date
    presentation: string
    is_public:
      type:       boolean
      default:    1
    image1:       string
    image2:       string
    artist_id:    integer

Track:
  actAs:
    Sluggable:
      fields: [name]
    Timestampable: ~
  columns:
    name:       string
    file_mp3:   string
    file_ogg:   string
    file_flac:  string
    release_id: integer

Post:
  actAs:
    Sluggable:
      fields: [title]
    I18n:
      fields: [body]
    Timestampable: ~
  columns:
    title:  string
    body:   string

Content:
  actAs:
    I18n:
      fields: [informations, credits, greetings]
    Timestampable: ~
  columns:
    informations: string
    credits:      string
    greetings:    string
    video:        string
    links:        string